[package]
name = "mdbook-linkcheck"
version = "0.1.3-alpha.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A backend for `mdbook` which will check your links for you."
license = "MIT"
documentation = "https://docs.rs/mdbook-linkcheck"
repository = "https://github.com/Michael-F-Bryan/mdbook-linkcheck"
readme = "README.md"

[package.metadata.release]
sign-commit = true

[[bin]]
name = "mdbook-linkcheck"
path = "src/bin/mdbook-linkcheck.rs"
doc = false

[dependencies]
mdbook = "0.2"
serde = "1.0"
serde_derive = "1.0"
failure = "0.1"
serde_json = "1.0"
pulldown-cmark = "0.1"
structopt = "0.2"
log = "0.4"
env_logger = "0.5"
memchr = "2.0"
url = "1.6"
reqwest = "0.8"

[dev-dependencies]
pretty_assertions = "0.5"
