[package]
name = "mdbook-linkcheck"
version = "0.3.2-alpha.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "A backend for `mdbook` which will check your links for you."
license = "MIT"
edition = "2018"
documentation = "https://docs.rs/mdbook-linkcheck"
repository = "https://github.com/Michael-F-Bryan/mdbook-linkcheck"
readme = "README.md"

[[bin]]
name = "mdbook-linkcheck"
path = "src/bin/mdbook-linkcheck.rs"
doc = false

[dependencies]
mdbook = { version = "0.3", default-features = false }
serde = "1.0"
serde_derive = "1.0"
failure = "0.1"
serde_json = "1.0"
pulldown-cmark = "0.5"
structopt = "0.2"
log = "0.4"
env_logger = "0.6"
semver = "0.9.0"
regex = "1.0"
codespan = "0.3.0"
codespan-reporting = "0.3.0"
url = "1.7.2"

[dev-dependencies]
pretty_assertions = "0.6"
toml = "0.5"
